import { useCallback, useEffect, useRef, useMemo, useState } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { useNavigate } from 'react-router-dom'
import Can from '../components/Can'
import SessionManager from '../components/SessionManager'
import { actualizarTipoInventario, crearTipoInventario, obtenerTiposInventario } from '../services/inventoryApi'
import { emptyType, PAGE_SIZE } from './InventoryUtils'
import { EmptyState, SearchBar, TableTypes, TypeModal } from './InventoryShared'

const PAGE_SIZES = [5, 10, 20, 50]
const Paginacion = ({ total, page, pageSize, onPageChange }) => { const pages = Math.max(1, Math.ceil(total / pageSize)); if (pages === 1) return null; return <div className="d-flex flex-wrap justify-content-between align-items-center gap-2 mt-3"><small className="text-muted">Página {page} de {pages}</small><div className="btn-group" role="group" aria-label="Paginación"><button type="button" className="btn btn-outline-secondary btn-sm" disabled={page === 1} onClick={() => onPageChange(page - 1)}>Anterior</button><button type="button" className="btn btn-outline-secondary btn-sm" disabled={page >= pages} onClick={() => onPageChange(page + 1)}>Siguiente</button></div></div> }

function InventoryTypesPage() {
  const { token, manejarSesionExpirada } = useAuth(); const navigate = useNavigate(); const tokenRef = useRef(token); const cargaInicialRef = useRef(false)
  const [tipos, setTipos] = useState([]); const [busqueda, setBusqueda] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(PAGE_SIZE); const [form, setForm] = useState(emptyType); const [editando, setEditando] = useState(null); const [modal, setModal] = useState(false); const [cargando, setCargando] = useState(true); const [guardando, setGuardando] = useState(false); const [mensaje, setMensaje] = useState(null)
  useEffect(() => { tokenRef.current = token }, [token])
  const cargar = useCallback(async () => { const tokenActual = tokenRef.current; if (!tokenActual) return; try { setCargando(true); const result = await obtenerTiposInventario(tokenActual); setTipos(Array.isArray(result) ? result : []); setMensaje(null) } catch (error) { if (error.status === 401) return manejarSesionExpirada(); setMensaje({ tipo: 'danger', texto: error.message || 'No fue posible cargar los tipos.' }) } finally { setCargando(false) } }, [manejarSesionExpirada])
  useEffect(() => { if (token && !cargaInicialRef.current) { cargaInicialRef.current = true; void cargar() } }, [token, cargar])
  const filtrados = useMemo(() => { const term = busqueda.trim().toLowerCase(); return term ? tipos.filter((item) => `${item.code} ${item.name}`.toLowerCase().includes(term)) : tipos }, [tipos, busqueda])
  const filas = useMemo(() => filtrados.slice((page - 1) * pageSize, page * pageSize), [filtrados, page, pageSize])
  const cerrar = () => { setModal(false); setEditando(null); setForm(emptyType) }; const editar = (item) => { setEditando(item.id); setForm({ code: item.code, name: item.name, active: item.active }); setModal(true) }
  const guardar = async (event) => { event.preventDefault(); setGuardando(true); setMensaje(null); try { const data = { ...form, code: form.code.trim().toUpperCase(), name: form.name.trim() }; if (editando) await actualizarTipoInventario(editando, data, token); else await crearTipoInventario(data, token); await cargar(); setMensaje({ tipo: 'success', texto: editando ? 'Tipo actualizado correctamente.' : 'Tipo creado correctamente.' }); cerrar() } catch (error) { if (error.status === 401) manejarSesionExpirada(); else setMensaje({ tipo: 'danger', texto: error.message || 'No fue posible guardar el tipo.' }) } finally { setGuardando(false) } }
  return <><SessionManager token={token} onSesionExpirada={manejarSesionExpirada} /><div className="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><div className="d-flex align-items-center gap-2"><button type="button" className="btn btn-sm btn-link text-decoration-none p-0" onClick={() => navigate('/welcome')}>← Volver</button><h2 className="fw-bold mb-1">Tipos</h2></div><p className="text-muted mb-0">Administración de tipos de inventario.</p></div><Can permission="INVENTORY_CREATE"><button type="button" className="btn btn-primary" onClick={() => setModal(true)}>+ Nuevo tipo</button></Can></div>{mensaje && <div className={`alert alert-${mensaje.tipo}`} role="alert">{mensaje.texto}</div>}<div className="card shadow-sm border-0"><div className="card-body"><div className="d-flex flex-wrap align-items-center gap-2 mb-3"><SearchBar value={busqueda} onChange={(value) => { setBusqueda(value); setPage(1) }} /><label className="d-flex align-items-center gap-2 mb-0 ms-auto small text-muted">Mostrar<select className="form-select form-select-sm" style={{ width: 82 }} value={pageSize} onChange={(e) => { setPageSize(Number(e.target.value)); setPage(1) }}>{PAGE_SIZES.map((size) => <option key={size} value={size}>{size}</option>)}</select></label><span className="text-muted small">{filtrados.length} registros</span></div>{cargando && <div className="text-center py-5" role="status"><div className="spinner-border" /><div className="text-muted mt-2">Cargando tipos...</div></div>}{!cargando && filtrados.length === 0 && <EmptyState text="No hay tipos de inventario." />}{!cargando && filtrados.length > 0 && <><TableTypes rows={filas} onEdit={editar} /><Paginacion total={filtrados.length} page={page} pageSize={pageSize} onPageChange={setPage} /></>}</div></div>{modal && <TypeModal editando={Boolean(editando)} form={form} setForm={setForm} guardando={guardando} onClose={cerrar} onSubmit={guardar} />}</>
}
export default InventoryTypesPage