import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import Can from '../components/Can'
import { obtenerClientes } from '../services/clientsApi'
import { obtenerInventario, obtenerProductosInventario } from '../services/inventoryApi'
import { crearVenta, enviarFacturaPorCorreo } from '../services/salesApi'
import { abrirFactura } from '../utils/salesInvoice'

const money = (v) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(Number(v || 0))
const METHODS = ['EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'PSE', 'OTRO']

export default function SalesCheckoutPage() {
  const { token, manejarSesionExpirada } = useAuth(); const navigate = useNavigate()
  const [products, setProducts] = useState([]); const [inventory, setInventory] = useState([]); const [clients, setClients] = useState([])
  const [cart, setCart] = useState([]); const [search, setSearch] = useState(''); const [clientSearch, setClientSearch] = useState(''); const [mode, setMode] = useState('generic'); const [participants, setParticipants] = useState([])
  const [discount, setDiscount] = useState('0'); const [payments, setPayments] = useState([{ method: 'EFECTIVO', amount: '' }]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [sending, setSending] = useState(false); const [message, setMessage] = useState(null); const [lastSale, setLastSale] = useState(null)

  useEffect(() => { if (!token) return undefined; let cancelled = false; const load = async () => { try { const [p, i, c] = await Promise.all([obtenerProductosInventario(token, true), obtenerInventario(token), obtenerClientes(token, { page: 1, pageSize: 100 })]); if (cancelled) return; setProducts(Array.isArray(p) ? p : []); setInventory(Array.isArray(i) ? i : []); setClients(Array.isArray(c?.items) ? c.items : Array.isArray(c) ? c : []) } catch (e) { if (!cancelled) { if (e.status === 401) return manejarSesionExpirada(); setMessage({ type: 'danger', text: e.message || 'No fue posible cargar el punto de venta.' }) } } finally { if (!cancelled) setLoading(false) } }; void load(); return () => { cancelled = true } }, [manejarSesionExpirada, token])

  const stock = useMemo(() => new Map(inventory.map((i) => [i.product_id, i])), [inventory])
  const shownProducts = useMemo(() => { const t = search.trim().toLowerCase(); return products.filter((p) => !t || `${p.code || ''} ${p.name || ''}`.toLowerCase().includes(t)) }, [products, search])
  const subtotal = useMemo(() => cart.reduce((s, i) => s + Number(i.price) * Number(i.quantity), 0), [cart]); const discountValue = Math.min(100, Math.max(0, Number(discount) || 0)); const discountAmount = subtotal * discountValue / 100; const total = subtotal - discountAmount
  const paid = payments.reduce((s, p) => s + (Number(p.amount) || 0), 0); const difference = total - paid; const paidOk = Math.abs(difference) <= 0.01; const allocated = participants.reduce((s, p) => s + Number(p.percentage), 0); const remaining = Math.max(0, 100 - allocated)
  const filteredClients = useMemo(() => { const t = clientSearch.trim().toLowerCase(); const a = clients.filter((c) => !participants.some((p) => p.id === c.id)); return (t ? a.filter((c) => `${c.full_name || ''} ${c.identification_number || ''}`.toLowerCase().includes(t)) : a).slice(0, 8) }, [clientSearch, clients, participants])

  const addProduct = (product) => { const max = Number(stock.get(product.id)?.quantity || 0); if (max <= 0) return; setCart((c) => { const f = c.find((x) => x.product.id === product.id); if (!f) return [...c, { product, quantity: 1, price: Number(stock.get(product.id)?.sale_price || 0) }]; if (f.quantity >= max) return c; return c.map((x) => x.product.id === product.id ? { ...x, quantity: x.quantity + 1 } : x) }) }
  const changeQty = (id, delta) => setCart((c) => c.map((x) => x.product.id !== id ? x : { ...x, quantity: Math.min(Number(stock.get(id)?.quantity || 0), Math.max(0, x.quantity + delta)) }).filter((x) => x.quantity > 0))
  const addClient = (client) => { if (mode === 'client' && participants.length) return; if (mode === 'split' && remaining <= 0) return; setParticipants((p) => [...p, { ...client, percentage: remaining || 0 }]); setClientSearch('') }
  const removeClient = (id) => setParticipants((p) => p.filter((x) => x.id !== id)); const setClientPct = (id, value) => setParticipants((p) => p.map((x) => x.id === id ? { ...x, percentage: value } : x))
  const addPayment = () => { const r = Math.max(0, total - paid); setPayments((p) => [...p, { method: 'EFECTIVO', amount: r ? String(r) : '' }]) }; const removePayment = (i) => setPayments((p) => p.filter((_, n) => n !== i)); const setPayment = (i, field, value) => setPayments((p) => p.map((x, n) => n === i ? { ...x, [field]: value } : x))
  const reset = () => { setCart([]); setMode('generic'); setParticipants([]); setClientSearch(''); setDiscount('0'); setPayments([{ method: 'EFECTIVO', amount: '' }]) }

  const submit = async () => { if (!cart.length) return setMessage({ type: 'warning', text: 'Agrega al menos un producto a la venta.' }); if (mode === 'client' && participants.length !== 1) return setMessage({ type: 'warning', text: 'Selecciona un cliente registrado.' }); if (mode === 'split' && (participants.length < 2 || Math.abs(allocated - 100) > 0.01)) return setMessage({ type: 'warning', text: 'La distribución de clientes debe sumar exactamente 100 %.' }); if (!paidOk) return setMessage({ type: 'warning', text: difference > 0 ? 'Aún falta completar el pago de la venta.' : 'El pago supera el total de la venta.' }); setSaving(true); setMessage(null); try { const customers = mode === 'generic' ? [{ allocation_percentage: 100, is_generic: true }] : participants.map((p) => ({ client_id: p.id, allocation_percentage: Number(p.percentage), is_generic: false })); const sale = await crearVenta({ items: cart.map((x) => ({ product_id: x.product.id, quantity: x.quantity })), customers, payments: payments.map((p) => ({ payment_method: p.method, amount: Number(p.amount) })), discount_percentage: discountValue }, token); setLastSale(sale); reset(); setMessage({ type: 'success', text: `Venta ${sale.sale_number} realizada correctamente por ${money(sale.total)}.` }); const [p, i] = await Promise.all([obtenerProductosInventario(token, true), obtenerInventario(token)]); setProducts(Array.isArray(p) ? p : []); setInventory(Array.isArray(i) ? i : []) } catch (e) { if (e.status === 401) return manejarSesionExpirada(); setMessage({ type: 'danger', text: e.message || 'No fue posible registrar la venta.' }) } finally { setSaving(false) } }
  const print = () => { try { abrirFactura(lastSale) } catch (e) { setMessage({ type: 'warning', text: e.message }) } }
  const email = async () => { setSending(true); try { const r = await enviarFacturaPorCorreo(lastSale.id, token); setMessage({ type: 'success', text: `Factura enviada a ${r.recipients.join(', ')}.` }) } catch (e) { if (e.status === 401) return manejarSesionExpirada(); setMessage({ type: e.status === 503 ? 'warning' : 'danger', text: e.message || 'No fue posible enviar la factura.' }) } finally { setSending(false) } }

  if (loading) return <div className="text-center py-5"><div className="spinner-border" /><div className="text-muted mt-2">Preparando punto de venta...</div></div>
  return <>
    <div className="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h2 className="fw-bold mb-1">🛒 Punto de venta</h2><p className="text-muted mb-0">Selecciona productos, cliente, descuento y forma de pago en una sola pantalla.</p></div><div className="d-flex gap-2"><button className="btn btn-outline-primary" onClick={() => navigate('../ventas/consulta')}>📋 Consultar ventas</button><button className="btn btn-outline-secondary" onClick={reset} disabled={saving}>Nueva venta</button></div></div>
    {message && <div className={`alert alert-${message.type}`}>{message.text}</div>}
    {lastSale && <div className="card shadow-sm border-0 mb-4"><div className="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><strong>🧾 Venta {lastSale.sale_number}</strong><div className="text-muted">Total: {money(lastSale.total)}</div></div><div className="d-flex gap-2 flex-wrap"><button className="btn btn-outline-secondary" onClick={print}>🖨️ Imprimir factura</button><Can permission="SALES_EMAIL"><button className="btn btn-primary" onClick={() => void email()} disabled={sending}>{sending ? 'Enviando...' : '✉️ Enviar factura'}</button></Can><button className="btn btn-outline-primary" onClick={() => navigate('../ventas/consulta')}>📋 Ver ventas</button></div></div></div>}
    <div className="row g-4"><div className="col-xl-8"><div className="card shadow-sm border-0 mb-4"><div className="card-body"><div className="input-group input-group-lg"><span className="input-group-text">🔎</span><input className="form-control" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar por nombre o código..." /></div></div></div><div className="row g-3">{shownProducts.map((p) => { const q = Number(stock.get(p.id)?.quantity || 0); const price = Number(stock.get(p.id)?.sale_price || 0); return <div className="col-sm-6 col-lg-4" key={p.id}><button className="card h-100 w-100 text-start border-0 shadow-sm overflow-hidden" onClick={() => addProduct(p)} disabled={!q}>{p.image_url ? <img src={p.image_url} alt={p.name} className="w-100" style={{ height: 170, objectFit: 'cover' }} /> : <div className="d-flex align-items-center justify-content-center bg-body-tertiary" style={{ height: 170, fontSize: 52 }}>📦</div>}<div className="card-body"><div className="d-flex justify-content-between gap-2 mb-3"><span className="small text-muted">{p.code}</span><span className={q ? 'badge text-bg-success' : 'badge text-bg-secondary'}>{q ? `${q} disponibles` : 'Sin stock'}</span></div><div className="fw-bold">{p.name}</div><div className="mt-3 fw-bold fs-5">{money(price)}</div></div></button></div> })}</div></div>
      <div className="col-xl-4"><div className="card shadow-sm border-0 position-sticky" style={{ top: 20 }}><div className="card-header bg-white fw-bold fs-5">🧾 Tu venta</div><div className="card-body">{!cart.length && <div className="text-center text-muted py-4">Tu carrito está vacío.<br />Selecciona productos para comenzar.</div>}{cart.map((x) => <div className="border-bottom py-3" key={x.product.id}><div className="fw-semibold">{x.product.name}</div><div className="small text-muted">{money(x.price)} c/u</div><div className="d-flex justify-content-between align-items-center mt-2"><div className="btn-group"><button className="btn btn-outline-secondary btn-sm" onClick={() => changeQty(x.product.id, -1)}>−</button><span className="btn btn-light btn-sm">{x.quantity}</span><button className="btn btn-outline-secondary btn-sm" onClick={() => changeQty(x.product.id, 1)}>+</button></div><strong>{money(x.price * x.quantity)}</strong></div></div>)}
        <hr /><label className="form-label fw-semibold">👥 Cliente(s)</label><div className="btn-group w-100 mb-2"><button className={`btn ${mode === 'generic' ? 'btn-primary' : 'btn-outline-primary'}`} onClick={() => setMode('generic')}>Consumidor final</button><button className={`btn ${mode === 'client' ? 'btn-primary' : 'btn-outline-primary'}`} onClick={() => setMode('client')}>Un cliente</button><button className={`btn ${mode === 'split' ? 'btn-primary' : 'btn-outline-primary'}`} onClick={() => setMode('split')}>Dividir</button></div>{mode !== 'generic' && <><input className="form-control mb-2" value={clientSearch} onChange={(e) => setClientSearch(e.target.value)} placeholder="Buscar cliente..." /><div className="list-group mb-2">{filteredClients.map((c) => <button type="button" className="list-group-item list-group-item-action" key={c.id} onClick={() => addClient(c)}>{c.full_name}</button>)}</div>{participants.map((p) => <div className="border rounded p-2 mb-2" key={p.id}><div className="d-flex justify-content-between"><strong className="small">{p.full_name}</strong><button className="btn btn-sm btn-outline-danger" onClick={() => removeClient(p.id)}>×</button></div><div className="input-group input-group-sm mt-2"><input type="number" min="0.01" max="100" step="0.01" className="form-control" value={p.percentage} onChange={(e) => setClientPct(p.id, e.target.value)} /><span className="input-group-text">%</span></div></div>)}{mode === 'split' && <div className={`alert py-2 ${Math.abs(allocated - 100) < .01 ? 'alert-success' : 'alert-warning'}`}>{Math.abs(allocated - 100) < .01 ? '✓ Distribución al 100 %' : `Faltan ${remaining.toFixed(2)} %`}</div>}</>}
        <label className="form-label fw-semibold">🏷️ Descuento (%)</label><input type="number" min="0" max="100" step="0.01" className="form-control mb-3" value={discount} onChange={(e) => setDiscount(e.target.value)} />
        <div className="d-flex justify-content-between align-items-center mb-2"><label className="form-label fw-semibold mb-0">💳 Pagos</label><button className="btn btn-sm btn-outline-primary" onClick={addPayment}>+ Agregar pago</button></div>{payments.map((p, i) => <div className="input-group mb-2" key={`${p.method}-${i}`}><select className="form-select" value={p.method} onChange={(e) => setPayment(i, 'method', e.target.value)}>{METHODS.map((m) => <option key={m}>{m}</option>)}</select><input type="number" min="0.01" step="0.01" className="form-control" value={p.amount} onChange={(e) => setPayment(i, 'amount', e.target.value)} placeholder="Valor" />{payments.length > 1 && <button className="btn btn-outline-danger" onClick={() => removePayment(i)}>×</button>}</div>)}<div className={`small ${paidOk ? 'text-success' : 'text-warning'}`}>{paidOk ? '✓ Pago completo' : difference > 0 ? `Faltan ${money(difference)}` : `Excede ${money(Math.abs(difference))}`}</div>
        <div className="border-top pt-3 mt-3"><div className="d-flex justify-content-between"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="d-flex justify-content-between"><span>Descuento</span><span>- {money(discountAmount)}</span></div><div className="d-flex justify-content-between fs-4 fw-bold mt-2"><span>Total</span><span>{money(total)}</span></div></div><button className="btn btn-primary btn-lg w-100 mt-3" onClick={() => void submit()} disabled={saving || !cart.length}>{saving ? 'Guardando venta...' : 'Registrar venta'}</button>
      </div></div></div></div>
  </>
}
